services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: edgelogger
      POSTGRES_PASSWORD: development
      POSTGRES_DB: edgelogger
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: